//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testApp {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("testApp.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find.
        /// </summary>
        internal static string Cannot_find {
            get {
                return ResourceManager.GetString("Cannot_find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cannot find selected text.
        /// </summary>
        internal static string Cannot_find_selected {
            get {
                return ResourceManager.GetString("Cannot_find_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File doesn&apos;t exist!.
        /// </summary>
        internal static string File_exist {
            get {
                return ResourceManager.GetString("File_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на substrings with.
        /// </summary>
        internal static string many_replaced2 {
            get {
                return ResourceManager.GetString("many_replaced2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на substring with.
        /// </summary>
        internal static string one_replaced2 {
            get {
                return ResourceManager.GetString("one_replaced2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!Maybe you don&apos;t have a.
        /// </summary>
        internal static string pocket_err1 {
            get {
                return ResourceManager.GetString("pocket_err1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на pocket in your PC.
        /// </summary>
        internal static string pocket_err2 {
            get {
                return ResourceManager.GetString("pocket_err2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notebook replaced.
        /// </summary>
        internal static string replaced1 {
            get {
                return ResourceManager.GetString("replaced1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Do you want to save changes ?.
        /// </summary>
        internal static string Save_question {
            get {
                return ResourceManager.GetString("Save_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!Maybe you don&apos;t have a synthesizer pockets in your PC.
        /// </summary>
        internal static string Synth_err {
            get {
                return ResourceManager.GetString("Synth_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have unsaved changes. Do you want to exit? All unsaved changes will be deleted.
        /// </summary>
        internal static string Unsave_exit {
            get {
                return ResourceManager.GetString("Unsave_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have unsaved changes. Do you want to restart and change the language? All unsaved changes will be deleted.
        /// </summary>
        internal static string Unsave_lang {
            get {
                return ResourceManager.GetString("Unsave_lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have unsaved changes. Do you want to restart and change the theme? All unsaved changes will be deleted.
        /// </summary>
        internal static string Unsave_theme {
            get {
                return ResourceManager.GetString("Unsave_theme", resourceCulture);
            }
        }
    }
}
